// SPDX-License-Identifier: UNLICENSED

// This file is generated by POCtoUS
// Attacker:          {EOA}
// Attacker contract: {TARGET}
// TX hash:           {TX_HASH}
// Block number:      {BLOCK_NUMBER}

pragma solidity ^0.8.0;

import "forge-std/Test.sol";
{IMPORT_FILES}

{TARGET_CONTRACTS}

contract CallTest is Test {
    address public EOA = {EOA};
    address public target;
    bool success;
    bytes32 txHash = {TX_HASH};

    function setUp() public {
        target = address({TARGET});
        vm.createSelectFork('Anvil', {BLOCK_NUMBER} - 1);
    }

    function testMimicContractCall() public {
        vm.deal(EOA, EOA.balance);
        vm.startPrank(EOA, EOA);
        
        {INITIAL_CALL}
    }

}
